In [6]:
import pandas as pd
df = pd.read_excel("file/students.xlsx",index_col="번호")
# 데이터를 수집하면, 기본적으로 shape, describe, info는 해봐야 함
df.shape

(100, 8)

In [7]:
df.info

<bound method DataFrame.info of             이름    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  171  56  92  60       c
2       Kirbee   구로고   1  199  53  10  45       C
3    Appolonia   구로고   3  193  77  52  81       C
4        Avery   구로고   2  187  59  35  43       C
5       Dallis  디지털고   1  209  97  57  76       C
..         ...   ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고   3  187  91  63  59  Python
97        Nada   구로고   3  170  60  89  55  PYTHON
98       Fiona   신림고   1  200  97  95  84       C
99        Leif   구로고   2  192  96  84  34  PYTHON
100   Jonathan  디지털고   2  195  84  63  80    JAVA

[100 rows x 8 columns]>

In [8]:
df.describe()

               학년         키          국어          영어          수학
count  100.000000  100.0000  100.000000  100.000000  100.000000
mean     1.990000  185.4200   75.180000   48.380000   63.180000
std      0.797661   12.3175   13.929389   30.666265   17.490765
min      1.000000  161.0000   51.000000    0.000000   30.000000
25%      1.000000  176.7500   64.000000   22.000000   52.000000
50%      2.000000  186.5000   77.000000   44.000000   65.500000
75%      3.000000  194.2500   86.000000   76.250000   78.000000
max      3.000000  210.0000  100.000000   99.000000   90.000000

In [9]:
df = pd.read_excel("file/합계출산율_2026.xlsx",skiprows=28,nrows=2)
df

,Unnamed: 0,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,출생아 수,406.200,357.800,326.800,302.700,272.300,260.600,249.200,230.000,238.300,254.3
1,합계 출산율,1.172,1.052,0.977,0.918,0.837,0.808,0.778,0.721,0.748,0.8

In [10]:
df.columns

Index(['Unnamed: 0', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025'],
      dtype='str')

In [11]:
df.set_index("Unnamed: 0",inplace=True)
df

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
Unnamed: 0,,,,,,,,,,
출생아 수,406.200,357.800,326.800,302.700,272.300,260.600,249.200,230.000,238.300,254.3
합계 출산율,1.172,1.052,0.977,0.918,0.837,0.808,0.778,0.721,0.748,0.8

In [14]:
# 인덱스 이름 변경
df.index.name = "목록"
df

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
목록,,,,,,,,,,
출생아 수,406.200,357.800,326.800,302.700,272.300,260.600,249.200,230.000,238.300,254.3
합계 출산율,1.172,1.052,0.977,0.918,0.837,0.808,0.778,0.721,0.748,0.8