In [1]:
import pandas as pd
df = pd.read_excel("file/score.xlsx",index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
# import random

# for i in range(8):
#     df.iloc[i,9] = random.randint(0,5)
    
#     list = [0,1,2,3,4,5,6]
# a_arr = random.sample(list,k=8)
# # a_arr = random.randint(0,6)
# a_arr
# # df.shape
# # df['요일'] = a_arr

ValueError: Sample larger than population or is negative

In [ ]:
# 0-일요일, 1-월, 2-화 ... 6-토요일이 되도록 
# 출력하시오
# 함수 적용

import pandas as pd
import random

# def date(day): 
#     i = 0
#     for i in range(7):
#         day = ['일요일','월요일','화요일','수요일','목요일','금요일','토요일']
#         i += 1
#         print(f"{i},-,{day[i-1]}")

def cal_change(x):
    if x == 0: return '일요일'
    elif x == 1: return '월요일'
    elif x == 2: return '화요일'
    elif x == 3: return '수요일'
    elif x == 4: return '목요일'
    elif x == 5: return '금요일'
    elif x == 6: return '토요일'

TypeError: cal_change() missing 1 required positional argument: 'x'

In [32]:
import pandas as pd
data = {
    '번호':['1번','2번','3번','4번','5번','6번','7번','8번'],
    '이름':['홍길동','유관순','이순신','강감찬','김구','김유신','홍길자','홍길순'],
    '달러':['$19,700','$18,400','$16,800','$18,700','$18,800','$20,200','$18,800','$19,000'],
    '우대':[90,40,80,40,15,80,55,100]
}

df = pd.DataFrame(data)

In [33]:
# 1.금액 컬럼을 추가하시오.(금액 : 달러+달러*우대*0.01)
# 2.우대 50점 이상인 사람에게 달러+달러*우대*0.01
# 3.우대 50미만 달러

In [34]:
# 순서 : 달러 -> int로 변경

In [35]:
df1 = df['달러'].str.replace('$','')
df['달러'] = df1.str.replace(',','').astype(int)

df['우대'] = df['우대'].astype(int)
df

   번호   이름     달러   우대
0  1번  홍길동  19700   90
1  2번  유관순  18400   40
2  3번  이순신  16800   80
3  4번  강감찬  18700   40
4  5번   김구  18800   15
5  6번  김유신  20200   80
6  7번  홍길자  18800   55
7  8번  홍길순  19000  100

In [37]:
df['금액'] = df['달러']
df

   번호   이름     달러   우대     금액
0  1번  홍길동  19700   90  19700
1  2번  유관순  18400   40  18400
2  3번  이순신  16800   80  16800
3  4번  강감찬  18700   40  18700
4  5번   김구  18800   15  18800
5  6번  김유신  20200   80  20200
6  7번  홍길자  18800   55  18800
7  8번  홍길순  19000  100  19000

In [ ]:
# def money(dol):
#     if 

# # df.log[(df['우대']>=50), (df['달러'])] = df['달러']+df['우대']*0.01
# # df

AttributeError: 'DataFrame' object has no attribute 'log'

In [ ]:
# 서울~인천까지 총 인구수 합계

import pandas as pd
df = pd.read_csv("file/jumin08_2.csv")
df

,행정구역,2026년08월_총인구수,2026년08월_세대수,2026년08월_세대당 인구,2026년08월_남자 인구수,2026년08월_여자 인구수,2026년08월_남여 비율
0,전국 (1000000000),"51,084,159","24,505,258",2.08,"25,412,088","25,672,071",0.99
1,서울특별시 (1100000000),"9,281,625","4,525,061",2.05,"4,466,290","4,815,335",0.93
2,전남광주통합특별시 (1200000000),"3,155,803","1,579,291",2.00,"1,578,180","1,577,623",1.00
3,부산광역시 (2600000000),"3,229,467","1,583,256",2.04,"1,568,318","1,661,149",0.94
4,대구광역시 (2700000000),"2,346,277","1,123,265",2.09,"1,148,130","1,198,147",0.96
5,인천광역시 (2800000000),"3,066,185","1,418,345",2.16,"1,530,650","1,535,535",1.00
6,대전광역시 (3000000000),"1,442,838","706,437",2.04,"718,413","724,425",0.99
7,울산광역시 (3100000000),"1,086,373","502,387",2.16,"560,121","526,252",1.06
8,세종특별자치시 (3600000000),"390,738","165,930",2.35,"194,589","196,149",0.99
9,경기도 (4100000000),"13,773,918","6,189,087",2.23,"6,914,277","6,859,641",1.01
10,강원특별자치도 (5100000000),"1,506,662","775,882",1.94,"757,981","748,681",1.01
11,충청북도 (4300000000),"1,601,367","808,665",1.98,"816,717","784,650",1.04
12,충청남도 (4400000000),"2,138,938","1,072,860",1.99,"1,098,834","1,040,104",1.06
13,전북특별자치도 (5200000000),"1,716,965","874,337",1.96,"855,796","861,169",0.99
14,경상북도 (4700000000),"2,492,677","1,303,782",1.91,"1,262,786","1,229,891",1.03
15,경상남도 (4800000000),"3,191,645","1,558,906",2.05,"1,609,943","1,581,702",1.02
16,제주특별자치도 (5000000000),"662,681","317,767",2.09,"331,063","331,618",1.00

In [ ]:
t_pop = df['2026년08월_총인구수'].str.replace(",","").astype(int)
t_pop.info()
t_pop.describe()
t_pop.sum()

<class 'pandas.Series'>
RangeIndex: 17 entries, 0 to 16
Series name: 2026년08월_총인구수
Non-Null Count  Dtype
--------------  -----
17 non-null     int64
dtypes: int64(1)
memory usage: 268.0 bytes

np.int64(102168318)