In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('file/합계출산율_2026.xlsx',skiprows=28,nrows=2)
df.set_index('Unnamed: 0',inplace=True)
df.index.name='제목'
df

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
제목,,,,,,,,,,
출생아 수,406.200,357.800,326.800,302.700,272.300,260.600,249.200,230.000,238.300,254.3
합계 출산율,1.172,1.052,0.977,0.918,0.837,0.808,0.778,0.721,0.748,0.8

In [3]:
df.columns
df.index.values
df.index
df.index.values # index안에 유니코드까지 출력이 가능(index에서 육안으로 안보이는 코드까지 나타내주는 명령어)

<StringArray>
['출생아 수', '합계 출산율']
Length: 2, dtype: str

In [ ]:
df.iloc[:1]
df.loc['출생아 수'] # 컬럼 명에 보이지 않는 문자, 코드 있음 -> df.index.values로 확인해야 함 -> df.rename(index={"현재명":"고칠명"},inplace=True) 로 고쳐야 함

KeyError: '출생아 수'

In [5]:
df.index.values[0]

'출생아\xa0수'

In [6]:
# 인덱스에 포함된 코드를 제거
df.rename(index={"출생아\xa0수":"출생아 수"},inplace=True) # '출생아\xa0수'를 '출생아 수'로 변경
df.rename(index={"합게\xa0출산율":"합계 출산율"},inplace=True) #

In [7]:
df.index.values[1]

'합계\xa0출산율'

In [8]:
df.rename(index={'출생아\xa0수':"'출생아 수'"})

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
제목,,,,,,,,,,
출생아 수,406.200,357.800,326.800,302.700,272.300,260.600,249.200,230.000,238.300,254.3
합계 출산율,1.172,1.052,0.977,0.918,0.837,0.808,0.778,0.721,0.748,0.8

In [9]:
df = df.T # row, column 축을 변경 -> 행과 열을 바꿈
df['출생아 수']

2016    406.2
2017    357.8
2018    326.8
2019    302.7
2020    272.3
2021    260.6
2022    249.2
2023    230.0
2024    238.3
2025    254.3
Name: 출생아 수, dtype: float64